### ISSUE TITLE
Make file fails on Video.js install

### ISSUE THREAD

**Issue by sk33lz** [heshanlk/OctopusVideo#8]
The file download location being used by the Drupal-org.make file does not exist anymore. It is breaking the install of the make file for me.

The new location is here, https://github.com/downloads/zencoder/video-js/video-js-3.0.7.zip, although they are using Github themselves now.

**Comment by amirdt22** [comment]
It seems the link was updated but for some reason still not working:

Unable to download video-js from                                     [error]
https://github.com/downloads/zencoder/video-js/video-js-3.0.7.zip.

That URL above works for me when I try to download it via chrome.

Also strange, I had to modify distro.make to point to git:// instead of https:// github has 404 for this URL https://github.com/heidisoft/Octopus.git
